artifact_uri: /workspaces/zoomcamp/07-project/337591869417464722/cdf43cfc45fd403bbfd0eb6c0aff78ca/artifacts
end_time: 1725602433045
entry_point_name: ''
experiment_id: '337591869417464722'
lifecycle_stage: active
run_id: cdf43cfc45fd403bbfd0eb6c0aff78ca
run_name: mercurial-cat-215
run_uuid: cdf43cfc45fd403bbfd0eb6c0aff78ca
source_name: ''
source_type: 4
source_version: ''
start_time: 1725602294755
status: 4
tags: []
user_id: codespace
